src/Vjezba/Vjezba.Web/Areas/Admin/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vjezba.Web.Models;
using Vjezba.Model;
using Vjezba.DAL;

namespace Vjezba.Web.Areas.Admin.Controllers
{
    [RouteArea("Admin", AreaPrefix = "Administracija")]
    [RoutePrefix("Gradovi")]
    public class CityController : Controller
    {
        [Route("")]
        public ActionResult Index()
        {
            var context = new CompaniesManagerDbContext();
            var cities = context.Cities.ToList();
            context.Dispose();

            //Naziv view-a se automatski skuzi iz naziva akcije controller-a, dovoljno je proslijediti samo model
            return View(cities);
        }

        [Route("detalji")]
        public ActionResult Details(int? id = null)
        {
            if (id == null)
                return View();

            var context = new CompaniesManagerDbContext();
            var model = context.Cities.Find(id.Value);
            context.Dispose();

            return View(model);
        }

        [Route("detalji/info")]
        public ActionResult DetailsPartial(int? id = null)
        {
            if (id == null)
                return null;

            var context = new CompaniesManagerDbContext();
            var model = context.Cities.Find(id.Value);
            context.Dispose();

            if (model == null)
                return null;

            return PartialView("_DetailsPartial", model);
        }
    }

}

src/Vjezba/Vjezba.Web/Controllers/CompanyController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Ninject;
using Vjezba.DAL.Repository;
using Vjezba.Model;
using Vjezba.Web.Models;

namespace Vjezba.Web.Controllers
{
    [RequireHttps]
    public class CompanyController : Controller
    {
        [Inject]
        public CompanyRepository CompanyRepository { get; set; }

        [Inject]
        public CityRepository CityRepository { get; set; }

        public ActionResult Index()
        {
            return this.View(this.CompanyRepository.GetList(null));
        }

        [HttpPost]
        public ActionResult IndexAjax(CompanyFilterModel model)
        {
            return PartialView("_IndexTable", this.CompanyRepository.GetList(model));
        }

        public ActionResult Create()
        {
            this.FillDropDownValues();
            return View();
        }

        [HttpPost]
        public ActionResult Create(Company model)
        {
            if (ModelState.IsValid)
            {
                this.CompanyRepository.Add(model, autoSave: true);

                return RedirectToAction("Index");
            }
            else
            {
                this.FillDropDownValues();
                return View(model);
            }
        }

        public ActionResult Edit(int id)
        {
            this.FillDropDownValues();

            var model = this.CompanyRepository.Find(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditPost(int id)
        {
            var model = this.CompanyRepository.Find(id);
            var didUpdateModelSucceed = this.TryUpdateModel(model);

            if (didUpdateModelSucceed && ModelState.IsValid)
            {
                this.CompanyRepository.Update(model, autoSave: true);
                return RedirectToAction("Index");
            }

            this.FillDropDownValues();
            return View(model);
        }

        public ActionResult Details(int? id = null)
        {
            if (id == null)
                return View();

            var model = this.CompanyRepository.Find(id.Value);

            return View(model);
        }

        public JsonResult Delete(int id)
        {
            this.CompanyRepository.Delete(id);
            this.CompanyRepository.Save();

            return new JsonResult() { Data = "OK", JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        private void FillDropDownValues()
        {
            var possibleCities = this.CityRepository.GetList();

            var selectItems = new List<System.Web.Mvc.SelectListItem>();

            //Polje je opcionalno
            var listItem = new SelectListItem();
            listItem.Text = "- odaberite -";
            listItem.Value = "";
            selectItems.Add(listItem);

            foreach (var city in possibleCities)
            {
                listItem = new SelectListItem();
                listItem.Text = city.Name;
                listItem.Value = city.ID.ToString();
                listItem.Selected = false;
                selectItems.Add(listItem);
            }

            ViewBag.PossibleCities = selectItems;
        }
    }
}

src/Vjezba/Vjezba.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Pregled kompanija", "Index", "Company")</li>
                    <li>@Html.ActionLink("Pregled gradova", "Index", "City", new { area = "Admin" }, null)</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/globalize")
    @Html.Partial("_UICultureSetup")
    @RenderSection("scripts", required: false)
</body>
</html>

src/Vjezba/Vjezba.Web/Views/Shared/_UICultureSetup.cshtml
@{
    var culture = System.Threading.Thread.CurrentThread.CurrentCulture;
    var cultureCode = culture.TwoLetterISOLanguageName;
    var jsDatePattern = culture.DateTimeFormat.ShortDatePattern.ToUpper();
}

<script type="text/javascript">
    $.validator.methods.date = function (value, element) {
        if (this.optional(element) && (value == '' || value == undefined || value == null))
            return true;

        var shortDatePattern = '@jsDatePattern';

        return moment(value, shortDatePattern).isValid();
    }

    $.when(
        $.get("/scripts/cldr/data/@cultureCode/numbers.json"),
        $.get("/scripts/cldr/data/likelySubtags.json"),
        $.get("/scripts/cldr/data/numberingSystems.json")
    ).then(function () {
        // Normalize $.get results, we only need the JSON, not the request statuses.
        return [].slice.apply(arguments, [0]).map(function (result) {
            return result[0];
        });
    }).then(Globalize.load).then(function () {
        var globalizeNumberParser = Globalize('@cultureCode').numberParser();

        $.validator.methods.number = function (value, element) {
            if (this.optional(element))
                return true;

            if (!isNaN(globalizeNumberParser(value)))
                return true;

            return false;
        }

        $.validator.methods.range = function (value, element, param) {
            if (this.optional(element))
                return true;

            var val = globalizeNumberParser(value);

            return val >= param[0] && val <= param[1];
        }

    });

</script>

<script type="text/javascript">
    $(function () {
        $('.date-picker').datetimepicker({
            locale: '@cultureCode',
            format: '@jsDatePattern'
        });
    });
</script>